### ISSUE TITLE
compile error “make all”

### ISSUE THREAD

**Issue by cytl5yy** [SmartMeshFoundation/Spectrum#10]
github.com/SmartMeshFoundation/Spectrum/cmd/swarm
cmd/swarm/main.go:336:3: undefined: utils.NodeKeyFileFlag
cmd/swarm/main.go:337:3: undefined: utils.NodeKeyHexFlag
util.go:45: exit status 2
exit status 1
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by cc14514** [comment]
Thanks , already fix it on vsn 0.4.1
