### ISSUE TITLE
There are some issues with 0.2.1-beta

### ISSUE THREAD

**Issue by xiaofeizhu69** [SmartMeshFoundation/Spectrum#4]
This is the crash log .

INFO [04-08|22:39:14] Imported new chain segment               blocks=1   txs=1   mgas=0.030  elapsed=4.006ms   mgasps=7.388  number=128991 hash=1f5d32…b20fad
WARN [04-08|22:39:14] remove_fail_tx :                         hex=0x18e57689301351f34ba37bfe973dba1f4ef7ec636b3941dac2953f49eb7627d6 retry=8
fatal error: concurrent map read and map write

goroutine 66 [running]:
runtime.throw(0x103d090, 0x21)
	/usr/local/go1.9.2/src/runtime/panic.go:605 +0x95 fp=0xc4399a73c8 sp=0xc4399a73a8 pc=0x4418a5

**Comment by cc14514** [comment]
Thank you for your reminding. We are dealing with this problem.
