### ISSUE TITLE
Questions about debug.traceTransaction

### ISSUE THREAD

**Issue by xiaofeizhu69** [SmartMeshFoundation/Spectrum#5]
When I tried to track a transaction using debug.traceTransaction, the node suddenly crashed. Can you tell me what to do?
This is the error log.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xb02b86]

goroutine 10388463 [running]:
github.com/SmartMeshFoundation/Spectrum/eth.(*PrivateDebugAPI).TraceTransaction(0xc422824910, 0x194efa0, 0xc427eb6f90, 0x3a160a80c17bcaf8, 0xd97b6fdb788b6e1b, 0x1cdbae7817d5c310, 0x9d0fbb1e1b15b2e4, 0x0, 0x0, 0x0, ...)
	/home/ubuntu/Spectrum/build/_workspace/src/github.com/SmartMeshFoundation/Spectrum/eth/api_tracer.go:622 +0xf6
reflect.Value.call(0xc4233e2380, 0xc42000f678, 0x13, 0xffb9c0, 0x4, 0xc421a0d740, 0x4, 0x4, 0xffae35, 0xc421a0d740, ...)
	/usr/local/go1.9/src/reflect/value.go:434 +0x905
reflect.Value.Call(0xc4233e2380, 0xc42000f678, 0x13, 0xc421a0d740, 0x4, 0x4, 0x2, 0x2, 0xc42309b500)
	/usr/local/go1.9/src/reflect/value.go:302 +0xa4
github.com/SmartMeshFoundation/Spectrum/rpc.(*Server).handle(0xc4233bd220, 0x194efa0, 0xc427eb6f90, 0x1953d00, 0xc42174b860, 0xc421a0d6e0, 0xc426fbd140, 0xc422641860, 0x843693)
	/home/ubuntu/Spectrum/build/_workspace/src/github.com/SmartMeshFoundation/Spectrum/rpc/server.go:311 +0x6ce
github.com/SmartMeshFoundation/Spectrum/rpc.(*Server).exec(0xc4233bd220, 0x194efa0, 0xc427eb6f90, 0x1953d00, 0xc42174b860, 0xc421a0d6e0)
	/home/ubuntu/Spectrum/build/_workspace/src/github.com/SmartMeshFoundation/Spectrum/rpc/server.go:333 +0x1ba
github.com/SmartMeshFoundation/Spectrum/rpc.(*Server).serveRequest.func2(0xc42c7aa8c0, 0xc4233bd220, 0xc4233b25b0, 0x1953d00, 0xc42174b860, 0xc421433028, 0x1, 0x1, 0xc42002fc00)
	/home/ubuntu/Spectrum/build/_workspace/src/github.com/SmartMeshFoundation/Spectrum/rpc/server.go:206 +0xad
created by github.com/SmartMeshFoundation/Spectrum/rpc.(*Server).serveRequest
	/home/ubuntu/Spectrum/build/_workspace/src/github.com/SmartMeshFoundation/Spectrum/rpc/server.go:201 +0x2ab

**Comment by SmartMeshFoundation** [comment]
has add config= nil judgement
